import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillTwitterCircle, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import devanzy from "../public/anzy.jpg";
import backend from "../public/backend.png";
import fintech from "../public/banking.png";
import fullstack from "../public/app-development.png";
import desktop from "../public/desktop.png";
import dev from "../public/automated.png";
import debug from "../public/debugging.png";
import web1 from "../public/doowla.png";
import web2 from "../public/fitrackr.png";
import web3 from "../public/keyword.png";
import web4 from "../public/python-bot.png";
import web5 from "../public/gsca-blog.png";
import web6 from "../public/inventory.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Anderson Caleb Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-gray-200">
              Developedbyanzy
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="flex flex-col items-center p-5">
            <div className="relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-4 overflow-hidden md:h-96 md:w-96">
              <Image src={devanzy} layout="fill" objectFit="cover" />
            </div>
            <h2 className="text-md py-6 px-4 text-teal-600 font-semibold text-center md:text-xl max-w-4xl">
              I&apos;m Anderson Caleb — also known as <strong>Anzydev</strong> —
              a full-stack developer with a strong passion for backend
              development and scalable systems. Currently pursuing a software
              engineering diploma at Afrihub in Abuja, I specialize in building
              real-world fintech infrastructure, developer tools, and
              intelligent systems. My experience spans across PHP, JavaScript,
              TypeScript, Python, C#, Node.js, React, Next.js, SQL, and Git. I
              enjoy solving complex backend challenges and creating software
              that powers businesses from the ground up. I&apos;m the Technical
              Co-founder of <strong>Doowla</strong>, a modern financial
              infrastructure project aiming to rival Stripe and Flutterwave with
              features like multi-currency wallets, instant payouts, and smart
              APIs tailored for the African market. I also built{" "}
              <strong>FitTrackr</strong>, a desktop fitness tracker app written
              in C# (WPF) for a recent academic project. My goal? To build the
              next billion-dollar software company out of Africa — and to land a
              remote backend engineering role that fuels my growth toward
              becoming the next Zuck or Elon.
            </h2>

            <div className="text-5xl flex justify-center gap-16 py-4 text-gray-600">
              <a
                href="https://x.com/andersonanzy"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillTwitterCircle />
              </a>
              <a
                href="https://www.linkedin.com/in/anderson-caleb-06a58a314"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillLinkedin />
              </a>
            </div>
          </div>
        </section>

        <section>
          <div className="max-w-xl mx-auto">
            <h3 className="text-3xl py-3 text-center dark:text-gray-200">
              Services I offer
            </h3>
          </div>
          <div className="lg:flex justify-center gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <div className="flex justify-center">
                <Image src={backend} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Backend Development
              </h3>
              <p className="text-md text-center py-2 leading-8">
                API design & architecture (RESTful)
              </p>
              <p className="text-md text-center py-2 leading-8">
                Scalable and secure server-side logic
              </p>
              <p className="text-md text-center py-2 leading-8">
                Database modeling (SQL & NoSQL)
              </p>
              <p className="text-md text-center py-2 leading-8">
                Authentication systems (JWT, OAuth2, password reset, etc.)
              </p>
              <p className="text-md text-center py-2 leading-8">
                Refresh token and session management
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <div className="flex justify-center">
                <Image src={fintech} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Fintech API Development
              </h3>
              <p className="text-md text-center py-2 leading-8">
                Financial transaction systems
              </p>
              <p className="text-md text-center py-2 leading-8">
                Multi-currency wallet setup
              </p>
              <p className="text-md text-center py-2 leading-8">
                Instant payout logic
              </p>
              <p className="text-md text-center py-2 leading-8">
                Fraud detection prototypes
              </p>
              <p className="text-md text-center py-2 leading-8">
                Paystack / Flutterwave webhook integration
              </p>
              <p className="text-md text-center py-2 leading-8">
                Currency conversion logic
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <div className="flex justify-center">
                <Image src={fullstack} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Fullstack Web Applications
              </h3>
              <p className="text-md text-center py-2 leading-8">
                Building responsive apps with React / Next.js
              </p>
              <p className="text-md text-center py-2 leading-8">
                Backend integration using Node.js, Express, or Python FastAPI
              </p>
              <p className="text-md text-center py-2 leading-8">
                State management and data handling
              </p>
              <p className="text-md text-center py-2 leading-8">
                Building MVPs and admin dashboards
              </p>
            </div>
          </div>
          <div className="lg:flex justify-center gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <div className="flex justify-center">
                <Image src={desktop} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Desktop App Development
              </h3>
              <p className="text-md text-center py-2 leading-8">
                Windows apps using C# (WPF)
              </p>
              <p className="text-md text-center py-2 leading-8">
                Local data persistence with JSON
              </p>
              <p className="text-md text-center py-2 leading-8">
                User authentication and session control
              </p>
              <p className="text-md text-center py-2 leading-8">
                Real-world apps like FitTrackr
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <div className="flex justify-center">
                <Image src={dev} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Dev Tools & Automation
              </h3>
              <p className="text-md text-center py-2 leading-8">
                Git & GitHub project setup
              </p>
              <p className="text-md text-center py-2 leading-8">
                Version control for teams
              </p>
              <p className="text-md text-center py-2 leading-8">
                CLI tools and testing pipelines
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <div className="flex justify-center">
                <Image src={debug} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Testing & Debugging
              </h3>
              <p className="text-md text-center py-2 leading-8">
                Writing test plans and scripts
              </p>
              <p className="text-md text-center py-2 leading-8">
                Unit testing for Python / JS / C#
              </p>
              <p className="text-md text-center py-2 leading-8">
                Manual UI testing and edge case handling
              </p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-200">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-80 dark:text-gray-200">
              These are some of the cool things I’ve built so far — from fintech
              APIs to smart desktop apps. I love turning ideas into working
              software, and every project here shows a bit of what I’m
              passionate about.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <p className="text-md py-2 leading-8 text-gray-80 dark:text-gray-200">
                <strong>Doowla – Financial API Infrastructure</strong>
                <br />
                Doowla is a programmable bank backend designed for Africa,
                offering payment gateways, multi-currency wallets, real-time
                payouts, and developer-first APIs. It is built in Python, with
                plans for C#-powered transaction engines in production.
                <br />
                <strong>Stack:</strong> Python, FastAPI, PostgreSQL, REST API
                <br />
                <strong>Status:</strong> In development (Prototype ready)
                <br />
                <a
                  href="https://doowla.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-teal-500 underline"
                >
                  Doowla Home Page
                </a>
              </p>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <p className="text-md py-2 leading-8 text-gray-80 dark:text-gray-200">
                <strong>FitTrackr – Desktop Fitness Tracker App</strong>
                <br />
                Built in C# with WPF, FitTrackr is a beautiful desktop app that
                allows users to log activities, track calorie goals, view
                history, and persist data across sessions using JSON. Built for
                DDOOCP coursework.
                <br />
                <strong>Stack:</strong> C#, WPF
                <br />
                <strong>Status:</strong> Complete
                <br />
                <a
                  href="https://github.com/zuckworld/FitTrackr"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-teal-500 underline"
                >
                  FitTrackr GitHub Repo
                </a>
              </p>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <p className="text-md py-2 leading-8 text-gray-80 dark:text-gray-200">
                <strong>Telegram Keyword Finder</strong>
                <br />
                This is a simple desktop GUI app I built to search for specific
                keywords inside any Telegram group or channel I am part of.
                <br />
                <strong>Stack:</strong> Python
                <br />
                <strong>Status:</strong> Complete
                <br />
                <a
                  href="https://github.com/zuckworld/Keyword-Finder"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-teal-500 underline"
                >
                  Keyword Finder GitHub Repo
                </a>
              </p>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <p className="text-md py-2 leading-8 text-gray-80 dark:text-gray-200">
                <strong>Hybrid Python Trading Bot</strong>
                <br />
                An intelligent trading bot, designed to combine technical
                indicators with news sentiment analysis to make smarter trading
                decisions.
                <br />
                <strong>Stack:</strong> Python
                <br />
                <strong>Status:</strong> Complete
                <br />
                <a
                  href="#"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-teal-500 underline"
                >
                  This GitHub Repo is Private
                </a>
              </p>
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <p className="text-md py-2 leading-8 text-gray-80 dark:text-gray-200">
                <strong>Grace Skills Care Academy Blog</strong>
                <br />
                GSCA blog built with Next.js and Tailwind CSS, showcasing my
                frontend skills. This blog features a clean, modern design with
                responsive layouts and smooth animations.
                <br />
                <strong>Stack:</strong> Next.js, Tailwind CSS, Hygraph CMS
                <br />
                <strong>Status:</strong> Complete
                <br />
                <a
                  href="https://gscablog.vercel.app"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-teal-500 underline"
                >
                  Link to Gsca Blog
                </a>
              </p>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
              <p className="text-md py-2 leading-8 text-gray-80 dark:text-gray-200">
                <strong>Car Inventory</strong>
                <br />
                A clean and responsive car Inventory landing page built to
                showcase my frontend skills
                <br />
                <strong>Stack:</strong>HTML, JavaScript, Tailwind CSS
                <br />
                <strong>Status:</strong> Complete
                <br />
                <a
                  href="https://github.com/zuckworld/Car-inventory"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-teal-500 underline"
                >
                  Car Inventory GitHub Repo
                </a>
              </p>
            </div>
          </div>
        </section>
        <section>
          <h2 className="text-md py-6 px-4 text-teal-600 font-semibold text-center md:text-xl max-w-4xl">
            🎯 Goals
          </h2>
          <p className="text-md py-6 px-4 text-teal-600 font-semibold text-center md:text-xl max-w-4xl">
            Build scalable fintech APIs that solve African payment problems
            <br />
            Land a remote backend role to grow faster and contribute globally
            <br />
            Launch and scale Doowla to compete with Flutterwave & Stripe
            <br />
            Become a world-class software engineer
          </p>
          <h2 className="text-md py-6 px-4 text-teal-600 font-semibold text-center md:text-xl max-w-4xl">
            📫 Contact Me
          </h2>
          <a href="mailto:caleb1475@gmail.com">📧 Email: caleb1475@gmail.com</a>
          <a href="https://www.linkedin.com/in/anderson-caleb-06a58a314">
            🧑‍💼 LinkedIn: Anderson Caleb
          </a>
          <a href="https://github.com/zuckworld">🧑‍💻 GitHub: zuckworld</a>
          <a href="https://anzydev.vercel.app/">
            🌍 Portfolio: anzydev.vercel.app
          </a>
          <h2 className="text-md py-6 px-4 text-teal-600 font-semibold text-center md:text-xl max-w-4xl">
            ⚡ Fun Facts:
          </h2>
          <p className="text-md py-6 px-4 text-teal-600 font-semibold text-center md:text-xl max-w-4xl">
            I once built a trading bot from scratch.
            <br />
            My dream is to lead the African fintech revolution.
            <br />I love making complex logic feel simple.
          </p>
        </section>
      </main>
    </div>
  );
}
